### ISSUE TITLE
EPIC: Allow deephaven server to be started from python

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#2221]
- [ ] Make the Jetty-based server implementation easier to start with custom options, bindings
 - [x] Move bootstrap.py to test code, to be clear that this shouldn't be used to start the jvm under normal circumstances. It also probably should be pared down to be simpler to read and understand, as we practically never need that degree of customizability.
 - [x] Move existing top-level python projects into `py/`
 - [x] Create a new java application project with basic wiring to launch jetty for static content and gRPC services, designed to be easily called from python. This will involve cleaning up some currently rough edges in the dagger bindings, so that it is easier to build custom applications like this
 - [x] Create a new wheel project called `deephaven_server` which is able to start the jvm and the java components of Deephaven, including the engine and the gRPC service. This will have very little python in it, but will mostly be a container to hold the above java application, and will mostly offer the ability to start different parts of the server, as well as manipulate the script session or application
 - [ ] Ensure that `deephaven` has tools for working with the UGP
 - [ ] Update all wheel projects to publish working binaries to pypi, including jpy-deephaven (or jpy), deephaven, and deephaven_server.
 - [ ] Provide an optional custom UI experience where no console appears in the UI, but newly bound objects appear when the UI hears about them

**Comment by niloc132** [comment]
Incorrectly closed, this issue isn't complete yet.
