### ISSUE TITLE
EPIC: Deephaven server from python library follow-up

### ISSUE THREAD

**Issue by niloc132** [deephaven/deephaven-core#2453]
Follow up for #2221, to let that be closed when the work is finished

- [ ] Flexible "scope" support, rather than polling values from globals(). A specific "queryscope" object would be more pythonic, though perhaps harder to work with for most exploratory workflows
- [x] #4145
- [ ] Establish what configuration is possible/feasible for the jvm and deephaven's configuration, define a `@dataclass` for those details.
- [ ] Revisit how logs are handled, redirected, displayed, to be sure that if the web console is used at all, it sees what it would expect to see.

**Comment by chipkent** [comment]
I've created a repo to launch Deephaven as a Python library, while we wait for a full production version.
https://github.com/chipkent/test-dhaal

Everything is working, so no complaints.
